securelogx.enableMasking=true
securelogx.modelPath=onnx-model/ml-v1.3/bert-base-cased/model.onnx
securelogx.tokenizerPath=onnx-model/ml-v1.3/bert-base-cased/tokenizer.json
securelogx.model.sha256=5953acd999083fa08c17c537e1d88c38f3c7137bc518022d8f3246c1133997c2
securelogx.tokenizer.sha256=b30eb8ca04d00e5330bade5d5e6036bd0ce0ad68f7b96e2e38bff11942ee30b1
securelogx.model.maxSequenceLength=384


#If true, enable multithreaded tokenization (PureJavaTokenizer) and ONNX CPU threading
securelogx.cpu.multithreading.enabled=true
#If true, prefer CUDA GPU for ONNX inference
securelogx.gpu.inference.enabled=false



#CPU_SINGLE, CPU_MULTI, GPU, KAFKA
securelogx.mode=CPU_MULTI


# Increase thread count for CPU mode
securelogx.maxCpuThreads=4

# Optimized GPU settings
securelogx.gpu.batch.size=64
securelogx.gpu.warmup.enabled=true
securelogx.gpu.max.threads=4
securelogx.gpu.max.sequence.length=1024
securelogx.gpu.memory.pool.enabled=true

# Queue capacity optimizations
securelogx.inference.queue.capacity=200000

securelogx.kafka=false
securelogx.logFile=logs/securelogx.log
securelogx.environment=dev


# Kafka settings
kafka.bootstrap.servers=localhost:9092
kafka.topic=securelog.masking.input
kafka.group.id=securelogx-group
kafka.acks=all
kafka.compression.type=lz4
kafka.security.protocol=PLAINTEXT

securelogx.kafka.bootstrap.servers=localhost:9092
securelogx.kafka.group.id=securelogx-masking-group
securelogx.kafka.topic=raw-logs
securelogx.log.file=logs/securelogx.log
securelogx.kafka.consumer.enabled=true

# Processor (Compile-Time) Settings
processor.enableNer=false

# Optimized GPU settings
securelogx.gpu.batch.size=64
securelogx.gpu.warmup.enabled=true
securelogx.gpu.max.threads=1
securelogx.gpu.max.sequence.length=1024
securelogx.gpu.memory.pool.enabled=true

# Queue capacity optimizations
securelogx.inference.queue.capacity=200000

securelogx.kafka=false
securelogx.logFile=logs/securelogx.log
securelogx.environment=dev
securelogx.masking.onlyIn=dev
securelogx.showLastFour=true
